from . import crm_team
from . import customer_behavior_segment
from . import customer_behavior_config
from . import customer_behavior_analysis
from . import res_partner
from . import sale_order
from . import account_move
from . import account_payment
from . import account_payment_register
from . import customer_behavior_dashboard
from . import customer_behavior_recompute_wizard
