[options]
addons_path = C:\odoo14c\server\odoo\addons,C:\addon14
logfile = C:\addon14\log\odoo_upgrade_business_category.log
log_level = info
log_handler = :INFO
xmlrpc_port = 8071
db_host = localhost
db_port = 5432
db_user = openpg
db_password = openpgpwd
pg_path = C:\Odoo16\PostgreSQL\bin
