# -*- coding: utf-8 -*-

from . import controllers
from . import sapi
from . import payslip
from . import form_pkb
from . import form_pengobatan
from . import form_mutasi
from . import form_ib
from . import form_melahirkan
from . import form_sapi_masuk
from . import form_ganti_pemilik
from . import form_vaksinasi
from . import form_abortus
from . import form_speciment
from . import form_jenis_pengeringan
from . import form_kunjungan_kandang
from . import form_kunjungan_pemerahan
from . import form_kunjungan_dsb
from . import form_kunjungan_limbah
from . import form_kunjungan
from . import profil
from . import form_potong_kuku
from . import form_potong_tanduk
from . import form_nkt
from . import sampel_quartir
from . import form_palpasi_rektal
from . import profil_anggota
from . import profil_petugas
from . import form_kunjungan_pakan
from . import form_permohonan
from . import simpanan
from . import history_layanan
from . import list_history_kunjungan