{
    'name': 'GRT Asset Dairy Management',
    'version': '14.0.1.4.0',
    'summary': 'Pengelolaan asset biologis sapi perah',
    'category': 'Farm',
    'author': 'OpenAI',
    'license': 'LGPL-3',
    'depends': [
        'mail',
        'stock',
        'account',
        'om_account_asset',
        'master_sapi',
        'kandang',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/ir_cron_data.xml',
        'data/dairy_feed_reference_data.xml',
        'data/dairy_bcs_reference_data.xml',
        'views/res_config_settings_views.xml',
        'views/dairy_barn_views.xml',
        'views/dairy_cow_views.xml',
        'views/dairy_feeding_views.xml',
        'views/dairy_medical_stock_views.xml',
        'views/dairy_treatment_views.xml',
        'views/dairy_feed_reference_views.xml',
        'views/dairy_bcs_reference_views.xml',
        'views/dairy_valuation_views.xml',
        'wizard/dairy_bag_location_wizard_views.xml',
        'wizard/dairy_revaluation_wizard_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
}
