# -*- coding: utf-8 -*-

{
    'name': 'Odoo14 Payroll',
    'category': 'Generic Modules/Human Resources',
    'version': '14.0.1.0.0',
    'author': 'Odoo SA,Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'summary': 'Manage your employee payroll records',
    'images': ['static/description/banner.gif'],
    'description': "Odoo 14 Payroll, Payroll, Odoo 14,Odoo Payroll, Odoo Community Payroll",
    'depends': [
        'hr_contract',
        'hr_holidays',
        'hr_contract_types',
    ],
    'data': [
        'security/hr_payroll_security.xml',
        'security/ir.model.access.csv',
        'wizard/hr_payroll_payslips_by_employees_views.xml',
        'views/hr_contract_views.xml',
        'views/hr_salary_rule_views.xml',
        'views/hr_payslip_views.xml',
        'views/hr_employee_views.xml',
        'data/hr_payroll_sequence.xml',
        'views/hr_payroll_report.xml',
#       'data/hr_payroll_data.xml',
#		'data/hr_payroll_data1.xml',
#        'data/hr_payroll_data2.xml',
#        'data/hr_payroll_data3.xml',
#        'data/hr_payroll_data4.xml',
#		'data/hr_payroll_data5_code_BRTA_BJABTHB_PPH21_GU.xml',
#		'data/hr_payroll_data6_code_BJAB_PKP_PPhNK.xml',
#		'data/hr_payroll_data7_code_PPHSTH_PPHGJ_PPHTHRB.xml',
#		'data/hr_payroll_data8.xml',
#        'data/hr_payroll_data10.xml',
        'wizard/hr_payroll_contribution_register_report_views.xml',
        'views/res_config_settings_views.xml',
        'views/report_contributionregister_templates.xml',
        'views/report_payslip_templates.xml',
        'views/report_payslipdetails_templates.xml',
    ],
    'license': 'AGPL-3',
}
