# -*- coding: utf-8 -*-
{
    "name": "GRT Sales Business Category",
    "summary": "Business category and layered approval flow for sales orders",
    "description": """
Adds business category handling on Sales Orders using the same CRM teams/categories,
plus a two-step approval flow: Sales Team Leader then Accounting Manager.
""",
    "author": "PT Gagak Rimang Teknologi",
    "website": "https://rimang.id",
    "category": "Sales/Sales",
    "version": "14.0.1.0.11",
    "depends": [
        "sale_management",
        "sale_crm",
        "account",
        "contacts",
        "grt_crm_business_category",
    ],
    "post_init_hook": "post_init_hook",
    "data": [
        "data/res_partner_sequence.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
        "security/ir.rule.csv",
        "views/crm_business_category_views.xml",
        "views/customer_behavior_dashboard_views.xml",
        "views/customer_behavior_recompute_wizard_views.xml",
        "views/customer_behavior_segment_views.xml",
        "views/customer_behavior_config_views.xml",
        "views/customer_behavior_analysis_views.xml",
        "views/account_move_views.xml",
        "views/account_payment_views.xml",
        "views/res_partner_views.xml",
        "views/crm_team_views.xml",
        "views/sale_order_views.xml",
        "views/sale_team_menu_views.xml",
    ],
    "installable": True,
    "application": False,
}
