# -*- coding: utf-8 -*-
# Part of BrowseInfo. See LICENSE file for full copyright and licensing details.
from . import bed_transfer
from . import medical_diagnostic_hypotesis
from . import medical_patient_evaluation
from . import medical_diet_belief
from . import medical_diet_therapeutic
from . import medical_appointment
from . import medical_directions
from . import medical_patient_medication
from . import medical_patient_medication1
from . import medical_family_disease
from . import medical_icu_chest_drainage
from . import medical_icu_ecg
from . import medical_icu_glasgow
from . import medical_drug_route
from . import medical_icu_ventilation
from . import medical_inpatient_diet
from . import medical_inpatient_medication_admin_time
from . import medical_inpatient_medication_log
from . import medical_inpatient_medication
from . import medical_inpatient_registration
from . import medical_insurance_plan
from . import medical_insurance
from . import medical_lab_test_units
from . import medical_lab
from . import medical_medication_dosage
from . import medical_medicament
from . import medical_patient_lab_test
from . import medical_neomatal_apgar
from . import medical_dose_unit
from . import medical_prescription_order
from . import medical_pathology_category
from . import medical_pathology_group_member
from . import medical_pathology_group
from . import medical_pathology
from . import medical_patient_cage
from . import medical_patient_colposcopy_history
from . import medical_patient_disease
from . import medical_patient_diseases
from . import medical_patient_mammography_history
from . import medical_patient_menstrual_history
from . import medical_patient_pap_history
from . import medical_patient_pregnency
from . import medical_patient_prental_evolution
from . import medical_patient_psc
from . import medical_patient_rounding_medical_supply
from . import medical_patient_rounding_medicament
from . import medical_patient_rounding_vaccine
from . import medical_patient_rounding
from . import medical_patient
from . import medical_pediatrics_growth_charts_who
from . import medical_perinatal_monitor
from . import medical_physician
from . import medical_preinatal
from . import medical_prescription_line
from . import medical_puerperium_monitor
from . import medical_rcri
from . import medical_rounding_procedure
from . import medical_secondary_condition
from . import medical_signs_and_sympotoms
from . import medical_test_critearea
from . import medical_test_type
from . import medical_vaccitation
from . import pet_type
from . import psc_code
from . import res_partner
from . import medical_room
from . import medical_fasilitas
from . import deceased
from . import oprasi
from . import discharge_hospitalized
from . import pulang_paksa
from . import pulang_sendiri
from . import jenis_pelayanan
from . import master_jenis_mutasi
from . import master_vaksin
from . import master_tanda_kebuntingan
from . import master_posisi
from . import master_status_kesehatan
from . import master_status_reproduksi
from . import master_metoda
from . import master_abortus
from . import master_specimen
from . import master_specimen_tes
from . import master_pengeringan
from . import master_kategori_obat
from . import master_obat
from . import master_metoda_pengobatan
from . import master_alasan_potkuku
from . import master_alasan_palpasi
from . import master_temuan_uterus
from . import master_temuan_ovarium
from . import master_temuan_cervix
from . import master_tipe_sapi
from . import master_status_laktasi
from . import master_metode_perhitungan_jss
from . import master_kategori_penyakit
from . import master_kasus_penyakit
from . import master_kode_kelahiran
from . import master_keadaan_melahirkan
from . import master_kuman_sampel_kuartir
from . import master_kategori_breed
from . import master_breed
from . import master_pejantan
from . import master_semen_beku
from . import report_layanan
from . import inherit_modul



# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:s